api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    
    # Formats supportés
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    
    # Documentation
    docs_formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    
    # Interface de documentation
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
